name: Create Pre-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
    
jobs:

  create_prerelease:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: create prerelease
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: ${{ github.event.inputs.version }}
        prerelease: true
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
